# Generated by Django 3.0.8 on 2020-07-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entertainment_score', models.FloatField()),
                ('health_score', models.FloatField()),
                ('politics_score', models.FloatField()),
                ('sports_score', models.FloatField()),
                ('tech_score', models.FloatField()),
            ],
        ),
    ]
