# Generated by Django 3.0.8 on 2021-03-06 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordgame', '0002_auto_20200720_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='scorevector',
            name='blurb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordgame.Blurb'),
        ),
        migrations.CreateModel(
            name='PublicCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='wordgame.Creation')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
