# Generated by Django 3.0.8 on 2021-03-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordgame', '0003_auto_20210306_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='user',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
