# Generated by Django 3.0.8 on 2021-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_creation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencevector',
            name='category',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferencevector',
            name='score',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publiccreation',
            name='rank',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
