# Generated by Django 3.0.8 on 2021-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0005_auto_20210306_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='creation',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PublicCreation',
        ),
    ]
