# Generated by Django 3.0.8 on 2020-07-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blurb',
            name='entertainment_score',
        ),
        migrations.RemoveField(
            model_name='blurb',
            name='health_score',
        ),
        migrations.RemoveField(
            model_name='blurb',
            name='politics_score',
        ),
        migrations.RemoveField(
            model_name='blurb',
            name='sports_score',
        ),
        migrations.RemoveField(
            model_name='blurb',
            name='tech_score',
        ),
        migrations.CreateModel(
            name='ScoreVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_score', models.FloatField()),
                ('health_score', models.FloatField()),
                ('politics_score', models.FloatField()),
                ('sports_score', models.FloatField()),
                ('tech_score', models.FloatField()),
                ('blurb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordgame.Blurb')),
            ],
        ),
    ]
